// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: shared/communicate.proto

package shared

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Communicate_Initial_FullMethodName    = "/shared.Communicate/Initial"
	Communicate_InjectCall_FullMethodName = "/shared.Communicate/InjectCall"
)

// CommunicateClient is the client API for Communicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunicateClient interface {
	Initial(ctx context.Context, in *InitialRequest, opts ...grpc.CallOption) (*Empty, error)
	InjectCall(ctx context.Context, in *InjectCallRequest, opts ...grpc.CallOption) (*InjectCallResponse, error)
}

type communicateClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicateClient(cc grpc.ClientConnInterface) CommunicateClient {
	return &communicateClient{cc}
}

func (c *communicateClient) Initial(ctx context.Context, in *InitialRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Communicate_Initial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicateClient) InjectCall(ctx context.Context, in *InjectCallRequest, opts ...grpc.CallOption) (*InjectCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectCallResponse)
	err := c.cc.Invoke(ctx, Communicate_InjectCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicateServer is the server API for Communicate service.
// All implementations should embed UnimplementedCommunicateServer
// for forward compatibility.
type CommunicateServer interface {
	Initial(context.Context, *InitialRequest) (*Empty, error)
	InjectCall(context.Context, *InjectCallRequest) (*InjectCallResponse, error)
}

// UnimplementedCommunicateServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunicateServer struct{}

func (UnimplementedCommunicateServer) Initial(context.Context, *InitialRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initial not implemented")
}
func (UnimplementedCommunicateServer) InjectCall(context.Context, *InjectCallRequest) (*InjectCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectCall not implemented")
}
func (UnimplementedCommunicateServer) testEmbeddedByValue() {}

// UnsafeCommunicateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunicateServer will
// result in compilation errors.
type UnsafeCommunicateServer interface {
	mustEmbedUnimplementedCommunicateServer()
}

func RegisterCommunicateServer(s grpc.ServiceRegistrar, srv CommunicateServer) {
	// If the following call pancis, it indicates UnimplementedCommunicateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Communicate_ServiceDesc, srv)
}

func _Communicate_Initial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicateServer).Initial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communicate_Initial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicateServer).Initial(ctx, req.(*InitialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communicate_InjectCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicateServer).InjectCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communicate_InjectCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicateServer).InjectCall(ctx, req.(*InjectCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Communicate_ServiceDesc is the grpc.ServiceDesc for Communicate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Communicate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shared.Communicate",
	HandlerType: (*CommunicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initial",
			Handler:    _Communicate_Initial_Handler,
		},
		{
			MethodName: "InjectCall",
			Handler:    _Communicate_InjectCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/communicate.proto",
}
